config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :yorums
  resources :takipcis
  resources :posts
  get 'pages/about'

  get 'pages/home'

  root "demo#index"
  get 'admin', :to => "access#index"
  match ':controller(/:action(/:id))', :via => [:get, :post]
  

end

app/models/takipci.rb
class Takipci < ActiveRecord::Base
end

app/controllers/takipcis_controller.rb
class TakipcisController < ApplicationController
  before_action :set_takipci, only: [:show, :edit, :update, :destroy]

  # GET /takipcis
  # GET /takipcis.json
  def index
    @takipcis = Takipci.all
  end

  # GET /takipcis/1
  # GET /takipcis/1.json
  def show
  end

  # GET /takipcis/new
  def new
    @takipci = Takipci.new
  end

  # GET /takipcis/1/edit
  def edit
  end

  # POST /takipcis
  # POST /takipcis.json
  def create
    @takipci = Takipci.new(takipci_params)

    respond_to do |format|
      if @takipci.save
        format.html { redirect_to @takipci, notice: 'Takipci was successfully created.' }
        format.json { render :show, status: :created, location: @takipci }
      else
        format.html { render :new }
        format.json { render json: @takipci.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /takipcis/1
  # PATCH/PUT /takipcis/1.json
  def update
    respond_to do |format|
      if @takipci.update(takipci_params)
        format.html { redirect_to @takipci, notice: 'Takipci was successfully updated.' }
        format.json { render :show, status: :ok, location: @takipci }
      else
        format.html { render :edit }
        format.json { render json: @takipci.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /takipcis/1
  # DELETE /takipcis/1.json
  def destroy
    @takipci.destroy
    respond_to do |format|
      format.html { redirect_to takipcis_url, notice: 'Takipci was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_takipci
      @takipci = Takipci.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def takipci_params
      params.require(:takipci).permit(:ad, :soyad)
    end
end

app/helpers/takipcis_helper.rb
module TakipcisHelper
end

app/views/takipcis/_form.html.erb
<%= form_for(@takipci) do |f| %>
  <% if @takipci.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@takipci.errors.count, "error") %> prohibited this takipci from being saved:</h2>

      <ul>
      <% @takipci.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ad %><br>
    <%= f.text_field :ad %>
  </div>
  <div class="field">
    <%= f.label :soyad %><br>
    <%= f.text_field :soyad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/takipcis/edit.html.erb
<h1>Takipci Güncelleme</h1>

<%= render 'form' %>

<%= link_to 'Göster', @takipci %> |
<%= link_to 'Geri', takipcis_path %>

app/views/takipcis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Takipçiler</h1>

<table>
  <thead>
    <tr>
      <th>Ad</th>
      <th>Soyad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @takipcis.each do |takipci| %>
      <tr>
        <td><%= takipci.ad %></td>
        <td><%= takipci.soyad %></td>
        <td><%= link_to 'Göster', takipci %></td>
        <td><%= link_to 'Güncelle', edit_takipci_path(takipci) %></td>
        <td><%= link_to 'Sil', takipci, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Yeni Takipçi', new_takipci_path %>

app/views/takipcis/new.html.erb
<h1>Yeni Takipçi</h1>

<%= render 'form' %>

<%= link_to 'Geri', takipcis_path %>

app/views/takipcis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ad:</strong>
  <%= @takipci.ad %>
</p>

<p>
  <strong>Soyad:</strong>
  <%= @takipci.soyad %>
</p>

<%= link_to 'Güncelle', edit_takipci_path(@takipci) %> |
<%= link_to 'Geri', takipcis_path %>