config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :yorums
  resources :takipcis
  resources :posts
  get 'pages/about'

  get 'pages/home'

  root "demo#index"
  get 'admin', :to => "access#index"
  match ':controller(/:action(/:id))', :via => [:get, :post]
  

end

app/models/yorum.rb
class Yorum < ActiveRecord::Base
end

app/controllers/yorums_controller.rb
class YorumsController < ApplicationController
  before_action :set_yorum, only: [:show, :edit, :update, :destroy]

  # GET /yorums
  # GET /yorums.json
  def index
    @yorums = Yorum.all
  end

  # GET /yorums/1
  # GET /yorums/1.json
  def show
  end

  # GET /yorums/new
  def new
    @yorum = Yorum.new
  end

  # GET /yorums/1/edit
  def edit
  end

  # POST /yorums
  # POST /yorums.json
  def create
    @yorum = Yorum.new(yorum_params)

    respond_to do |format|
      if @yorum.save
        format.html { redirect_to @yorum, notice: 'Yorum was successfully created.' }
        format.json { render :show, status: :created, location: @yorum }
      else
        format.html { render :new }
        format.json { render json: @yorum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yorums/1
  # PATCH/PUT /yorums/1.json
  def update
    respond_to do |format|
      if @yorum.update(yorum_params)
        format.html { redirect_to @yorum, notice: 'Yorum was successfully updated.' }
        format.json { render :show, status: :ok, location: @yorum }
      else
        format.html { render :edit }
        format.json { render json: @yorum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yorums/1
  # DELETE /yorums/1.json
  def destroy
    @yorum.destroy
    respond_to do |format|
      format.html { redirect_to yorums_url, notice: 'Yorum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yorum
      @yorum = Yorum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yorum_params
      params.require(:yorum).permit(:yorum)
    end
end

app/helpers/yorums_helper.rb
module YorumsHelper
end

app/views/yorums/_form.html.erb
<%= form_for(@yorum) do |f| %>
  <% if @yorum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@yorum.errors.count, "error") %> prohibited this yorum from being saved:</h2>

      <ul>
      <% @yorum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :yorum %><br>
    <%= f.text_area :yorum %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/yorums/edit.html.erb
<h1>Editing Yorum</h1>

<%= render 'form' %>

<%= link_to 'Show', @yorum %> |
<%= link_to 'Back', yorums_path %>

app/views/yorums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Yorums</h1>

<table>
  <thead>
    <tr>
      <th>Yorum</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @yorums.each do |yorum| %>
      <tr>
        <td><%= yorum.yorum %></td>
        <td><%= link_to 'Show', yorum %></td>
        <td><%= link_to 'Edit', edit_yorum_path(yorum) %></td>
        <td><%= link_to 'Destroy', yorum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Yorum', new_yorum_path %>

app/views/yorums/new.html.erb
<h1>New Yorum</h1>

<%= render 'form' %>

<%= link_to 'Back', yorums_path %>

app/views/yorums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Yorum:</strong>
  <%= @yorum.yorum %>
</p>

<%= link_to 'Edit', edit_yorum_path(@yorum) %> |
<%= link_to 'Back', yorums_path %>